<div id=header>
  <div class="header">StattAuto :: Versicherungswesen</div>
  <div class="header-sub">Fallbeispiel im Spring-Seminar bei oose.</div>
</div>
<div id="menu">
	<ul class="liste">
		<li><a href="/">Willkommen</a></li>
	</u>
	<h2 id="admintitel">Admin</h2>
		<ul class="liste" id="adminmenu">
			<li><a href="datenLaden.mvc">Stammdaten laden</a></li>
			<li><a target="_blank" href="/h2-console">DB</a></li>
			<li><a target="_blank" href="http://localhost:8765">Admin Server</a></li>
			<li><a target="_blank" href="http://localhost:8500">Configuration</a></li>
			<li><a target="_blank" href="http://localhost:9411">Logging</a></li>
			<li><a target="_blank" href="http://localhost:8161">Messaging</a></li>
			<li><a target="_blank" href="http://localhost:8080">Security</a></li>
		</ul>
	<h2 id="mitgliedertitel">Mitglieder Verwaltung</h2>
	<ul class="liste" id="mitgliedermenu">
		<li><a href="http://localhost:9090/mitgliederverwaltung/mitglied/identifizieren">Mitglied identifizieren</a></li>
		<li><a href="http://localhost:9090/mitgliederverwaltung/mitgliederList">Mitglieder anzeigen</a></li>
		<li><a href="http://localhost:9090/mitgliederverwaltung/addMitglied">Mitglied aufnehmen</a></li>
	</ul>
	<h2 id="fuhrparktitel">Fuhrpark</h2>
	<ul class="liste" id="fuhrparkmenu">
		<li><a href="stationenanzeigen.mvc">Stationen anzeigen</a></li>
		<li><a href="stationanlegen.mvc">Station anlegen</a></li>
		<li><a href="kfzsanzeigen.mvc">Kfzs anzeigen</a></li>
		<li><a href="kfzanlegen.mvc">Kfz hinzuf&uuml;gen</a></li>
	</ul>
	<h2 id="callcentertitel">Call Center</h2>
	<ul class="liste" id="callcentermenu">
		<li><a href="http://localhost:9090/callcenter/reserviere">Kfz reservieren</a></li>
		<li><a href="reservierungenanzeigen.mvc">Reserv. bearbeiten</a></li>
	</ul>
	<h2 id="backofficetitel">Backoffice</h2>
	<ul class="liste" id="backofficemenu">
		<li><a href="rechnungenanzeigen.mvc">Rechnungen anzeigen</a></li>
		<li><a href="rechnungerstellen.mvc">Rechnungslauf starten</a></li>
	</ul>
</div>